# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [31]:
#1

import numpy as np

arr = np.random.uniform(0, 20, size=(4, 7))
max_val = np.max(arr)
min_val = np.min(arr)
a = 1 / (max_val - min_val)
b = -a * min_val
normalized_arr = a * arr + b

print(arr)
print(normalized_arr)

[[ 5.22514898 14.04876445 13.63727244  9.63243216  2.87075456  4.07350154
   7.09798551]
 [11.67507683 12.28720929  3.62361062  6.73791076  0.7994141  15.69376391
  18.39861827]
 [ 4.89073974 13.04168778 13.74623928  9.34686528  2.72225528 16.81648183
   8.79079653]
 [11.21564742 11.05949519  6.80676967  5.6535237  19.56049058  6.07229633
  13.98478795]]
[[0.23589984 0.70621483 0.68428154 0.47081616 0.11040627 0.1745149
  0.33572548]
 [0.57969289 0.61232068 0.15053489 0.31653283 0.         0.79389633
  0.93807006]
 [0.21807521 0.65253578 0.69008968 0.45559492 0.10249098 0.85373927
  0.42595543]
 [0.55520446 0.54688126 0.32020314 0.258733   1.         0.28105435
  0.70280476]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [32]:
#2

matrix = np.random.randint(0, 11, size=(8, 10))
row_sums = np.sum(matrix, axis=1)
min_row_index = np.argmin(row_sums)
min_row = matrix[min_row_index, :]
print("Минимальная сумма в строке с индексом", min_row_index)
print(min_row)


Минимальная сумма в строке с индексом 6
[4 0 9 9 1 1 5 1 0 1]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [33]:
#3

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
distance = np.linalg.norm(a - b)
print(distance)


5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [34]:
#4


A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = -np.linalg.inv(A) @ C @ np.linalg.inv(B)
print(X)


[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [35]:
#1

import numpy as np

data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32,skiprows=1)
print(data[:5, :])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [36]:
#2

mean = np.mean(data[:, 1:], axis=0)
min_val = np.min(data[:, 1:], axis=0)
max_val = np.max(data[:, 1:], axis=0)
median = np.median(data[:, 1:], axis=0)
print("Среднее значение: ", mean)
print("Минимум: ", min_val)
print("Максимум: ", max_val)
print("Медиана: ", median)


Среднее значение:  [2.16010017e+04 9.05528000e+00]
Минимум:  [0 1]
Максимум:  [2147483647         39]
Медиана:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [37]:
#3

q = 0.75
time_quantile = np.quantile(data[:, 1], q)
data[:, 1] = np.where(data[:, 1] > time_quantile, time_quantile, data[:, 1])
print(data)


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [38]:
#4

num_zero_times = np.sum(data[:, 1] == 0)
print("Количество рецептов со временем выполнения, равным 0: ", num_zero_times)
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])


Количество рецептов со временем выполнения, равным 0:  479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [39]:
#5

unique_recipes = np.unique(data[:, 0])
num_unique_recipes = len(unique_recipes)
print("Количество уникальных рецептов: ", num_unique_recipes)


Количество уникальных рецептов:  100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [40]:
#6

unique_ingredient_counts = np.unique(data[:, 2])
num_unique_ingredient_counts = len(unique_ingredient_counts)
print("Количество уникальных значений количества ингредиентов: ", num_unique_ingredient_counts)
print("Уникальные значения количества ингредиентов: ", unique_ingredient_counts)


Количество уникальных значений количества ингредиентов:  37
Уникальные значения количества ингредиентов:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [41]:
#7

less_than_5_ingredients = data[data[:, 2] <= 5]
print(less_than_5_ingredients)


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [42]:
#8

avg_ingredients_per_minute = data[:, 2] / data[:, 1]
print(avg_ingredients_per_minute)

max_avg_ingredients_per_minute = np.max(avg_ingredients_per_minute)
print(max_avg_ingredients_per_minute)


[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [43]:
#9

sorted_data = data[data[:, 1].argsort()[::-1]] # сортируем по убыванию времени выполнения
top_100 = sorted_data[:100]
avg_ingredients_top_100 = np.mean(top_100[:, 2])
print(avg_ingredients_top_100)


9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [44]:
#10
import random
import numpy as np

indices = random.sample(range(data.shape[0]), k=10)
random_recipes = data[indices]
print(random_recipes)



[[121507      5      3]
 [179325     40      6]
 [394176     65     12]
 [ 84049     38     13]
 [377194      7      6]
 [482123     45     11]
 [136825     45      8]
 [ 67057     65      4]
 [390602     65     14]
 [363748     65      5]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [45]:
#11

less_than_avg = data[data[:, 2] < np.mean(data[:, 2])]
percent_less_than_avg = len(less_than_avg) / len(data) * 100
print(percent_less_than_avg)


58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [46]:
#12

simple_recipes = np.logical_and(data[:, 1] <= 20, data[:, 2] <= 5)
simple_recipes = simple_recipes.astype(int)
data_with_simple_col = np.column_stack((data, simple_recipes))
print(data_with_simple_col)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [47]:
#13

num_simple_recipes = np.sum(data_with_simple_col[:, 3])
total_recipes = data_with_simple_col.shape[0]
percent_simple_recipes = (num_simple_recipes / total_recipes) * 100
print("Процент простых рецептов: ", percent_simple_recipes)


Процент простых рецептов:  9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [48]:
#14

short_recipes = data[data[:, 1] < 10]
standard_recipes = data[np.logical_and(data[:, 1] >= 10, data[:, 1] <= 20)]
long_recipes = data[data[:, 1] > 20]

max_num_recipes = min(len(short_recipes), len(standard_recipes), len(long_recipes))
short_recipes = short_recipes[:max_num_recipes]
standard_recipes = standard_recipes[:max_num_recipes]
long_recipes = long_recipes[:max_num_recipes]

recipes_array = np.zeros((3, max_num_recipes, 3), dtype='int32')
recipes_array[0, :, :] = short_recipes
recipes_array[1, :, :] = standard_recipes
recipes_array[2, :, :] = long_recipes

print(recipes_array.shape)


(3, 7588, 3)
